---
# Source: operator/templates/operator-roles.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-operator
  namespace: mongodb-operator---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator
rules:
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - update
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
      - deletecollection
  - apiGroups:
      - mongodb.com
    verbs:
      - '*'
    resources:
      - mongodb
      - mongodb/finalizers
      - mongodbusers
      - opsmanagers
      - opsmanagers/finalizers
      - mongodbmulticluster
      - mongodbmulticluster/finalizers
      - mongodb/status
      - mongodbusers/status
      - opsmanagers/status
      - mongodbmulticluster/status
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - list
      - watch
---
# Source: operator/templates/operator-roles.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator-webhook
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
# Source: operator/templates/operator-roles.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-operator
subjects:
  - kind: ServiceAccount
    name: mongodb-operator
    namespace: mongodb-operator

# This ClusterRoleBinding is necessary in order to use validating
# webhooks—these will prevent you from applying a variety of invalid resource
# definitions. The validating webhooks are optional so this can be removed if
# necessary.
---
# Source: operator/templates/operator-roles.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-operator-webhook-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mongodb-operator-webhook
subjects:
  - kind: ServiceAccount
    name: mongodb-operator
    namespace: mongodb-operator
---
# Source: operator/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-operator
  namespace: mongodb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: mongodb-operator
      app.kubernetes.io/instance: mongodb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: mongodb-operator
        app.kubernetes.io/instance: mongodb-operator
    spec:
      serviceAccountName: mongodb-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      containers:
        - name: mongodb-operator
          image: "custom.repo/data/mongodb-operator-ubi:1.22.0-amd64"
          imagePullPolicy: Always
          args:
            - -watch-resource=mongodb
            - -watch-resource=opsmanagers
            - -watch-resource=mongodbusers
          command:
            - /usr/local/bin/mongodb-operator
          resources:
            limits:
              cpu: 1100m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 200Mi
          env:
            - name: OPERATOR_ENV
              value: prod
            - name: WATCH_NAMESPACE
              value: "*"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CLUSTER_CLIENT_TIMEOUT
              value: "10"
            - name: IMAGE_PULL_POLICY
              value: Always
            # Database
            - name: MONGODB_ENTERPRISE_DATABASE_IMAGE
              value: custom.repo/data/mongodb-database-ubi
            - name: INIT_DATABASE_IMAGE_REPOSITORY
              value: custom.repo/data/mongodb-init-database-ubi
            - name: INIT_DATABASE_VERSION
              value: 1.0.19-amd64
            - name: DATABASE_VERSION
              value: 2.0.2-amd64
            # Ops Manager
            - name: OPS_MANAGER_IMAGE_REPOSITORY
              value: custom.repo/data/mongodb-ops-manager-ubi
            - name: INIT_OPS_MANAGER_IMAGE_REPOSITORY
              value: custom.repo/data/mongodb-init-ops-manager-ubi
            - name: INIT_OPS_MANAGER_VERSION
              value: 1.0.12-amd64
            # AppDB
            - name: INIT_APPDB_IMAGE_REPOSITORY
              value: custom.repo/data/mongodb-init-appdb-ubi
            - name: INIT_APPDB_VERSION
              value: 1.0.18-amd64
            - name: OPS_MANAGER_IMAGE_PULL_POLICY
              value: Always
            - name: AGENT_IMAGE
              value: "custom.repo/data/mongodb-agent-ubi:12.0.25.7724-1-amd64"
            - name: MONGODB_IMAGE
              value: mongodb-server
            - name: MONGODB_REPO_URL
              value: custom.repo/data
            - name: MDB_IMAGE_TYPE
              value: ubi8
            - name: PERFORM_FAILOVER
              value: 'true'
